# -*- Makefile -*-

CC = clang
CXX = -Wall

all: p1 p2 p3 p4 p5

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe p5.exe
	rm -f p1 p2 p3 p4 p5

p1: CSE\ ASS\ 3\ Prob\ 1.c

	$(CC) $(CXX) -o $@ "$^"

p2: CSE\ ASS\ 3\ Prob\ 2.c

	$(CC) $(CXX) -o $@ "$^"

p3: CSE\ ASS\ 3\ Prob\ 3.c

	$(CC) $(CXX) -o $@ "$^"

p4: CSE\ ASS\ 3\ Prob\ 4.c

	$(CC) $(CXX) -o $@ "$^"

p5: CSE\ ASS\ 3\ Prob\ 5.c

	$(CC) $(CXX) -o $@ "$^"
