# -*- Makefile -*-

CC = clang
CXX = -Wall

all: p1 p2 p3

clean:

	rm -f p1.exe p2.exe p3.exe
	rm -f p1 p2 p3

p1: CSE\ ASS\ 5\ Prob\ 1\ -\ Part\ 1.c

	$(CC) $(CXX) -o $@ "$^"

p2: CSE\ ASS\ 5\ Prob\ 2\ -\ Part\ 1.c

	$(CC) $(CXX) -o $@ "$^"

p3: CSE\ ASS\ 5\ Prob\ 3\ -\ Part\ 1.c

	$(CC) $(CXX) -o $@ "$^"
